package com.avr.apps.docgen.service.interfaces;

public enum Docgen {
  QUOTATION,
  ORDER_CUSTOMER,
  SALE_ORDER_PROFORMA,
  INVOICE,
  PURCHASE_ORDER_ORDER,
  INVOICE_PROFORMA,
  INVOICE_REFUNDS,
  STOCK_MOVE_DELIVERY_NOTE,
  STOCK_MOVE_RETURN_VOUCHER,
  CONTRACT,
  LOGISTICAL_FORM,
  LOGISTICAL_FORM_WITHOUT_COMPOSITE,
}
